[workspace]
resolver = "2"

members = ["day-*"]

[workspace.dependencies]
miette = { version = "5.10", features = ["fancy"] }
thiserror = "1.0.50"
itertools = "0.12.0"
nom = "7.1.3"
indicatif = { version = "0.17.7", features = ["rayon"] }
rayon = "1.8.0"
